<script setup lang="ts">
import { shallowRef, onMounted, onBeforeUnmount } from "vue";
import { useWindowSize } from "@vueuse/core";
import { useLoop } from "@tresjs/core";
import type { Group } from "three";
import {
  approach,
  clamp01,
  createDots,
  createLinkPool,
  createLines,
  drawFraction,
  easeOutCubic,
  rand01,
  setDotScale,
  smoothstep,
  type DotField,
  type LineField,
  type LinkPool,
  type SetPieceProps,
} from "./lineArt";

/**
 * The Maastricht chapter's backdrop: the master thesis, played back.
 *
 * Every structure here was generated by the GAN from the AIIDE 2023 paper,
 * picked from the 8,000-level evaluation set among the ones Science Birds
 * itself measured as STABLE. Each one goes through the pipeline the thesis
 * describes, then gets what every Angry Birds structure is for:
 *
 *   1. **Noise → grid.** A field of flickering dots (the latent noise) resolves
 *      into the structure's raster: the GAN's output is an image, one cell per
 *      0.22 m, the smallest block's edge.
 *   2. **Grid → blocks.** The image is decoded into real blocks, which drop
 *      into place bottom-up, wood/ice/stone tinted, pigs last.
 *   3. **Bird.** A bird leaves the slingshot, trailing puffs, and knocks it
 *      down.
 *
 * The collapse is not simulated here. `scripts/bake-structures.mjs` ran it
 * once in Box2D and stored every body's pose at 20 fps
 * (`public/setpieces/structures.json`, ~12 KB gzipped); this piece only
 * interpolates. That keeps a physics engine out of the bundle, and every
 * visitor sees the same collapse.
 *
 * Unlike the other milestone backdrops the levels run on a CLOCK, not on
 * scroll: one card's scroll could never hold more than a level or two, and the
 * point is that there are many. The clock only runs while the piece is visible
 * and restarts at "noise" each time it comes back, on the next level.
 * `cardProgress` still draws the ground and slingshot on, house style.
 */
const props = withDefaults(defineProps<SetPieceProps>(), {
  reveal: 0,
  variant: "",
  position: () => [0, 0, 0],
  cardProgress: undefined,
});

const { pointer } = usePointer();
const { reducedMotion } = usePreferences();
const { height } = useWindowSize();

const DATA_URL = "/setpieces/structures.json";

// Materials in the bake's order: wood, ice, stone. Science Birds' own colours,
// lifted so they read additively on the dark scene.
const MATERIAL_COLORS = ["#ffb86b", "#7fe7ff", "#c9c3e6"];
const PIG = "#9df59d";
const BIRD = "#ff7a7a";
const RIG = "#c4a0ff"; // ground + slingshot, in the chapter's accent
const HOT = "#ffffff";
const HILLS = "#8fd19e";

/** Game metres → stage units. A level plus its slingshot is ~12 m across. The
 *  card steps the head back (`headDepth` in 30-maastricht.md) to make room. */
const STAGE_SCALE = 0.155;
/** Where the stage stands relative to the slot position (stage units). */
const STAGE_OFFSET: [number, number, number] = [0.04, -0.56, -0.3];
/**
 * The stage is seen from slightly above, so the blocks' tops show and their
 * depth reads (Science Birds itself is flat). No yaw at rest: a turned stage
 * brings one end of a 13 m ground strip toward the camera, and since the strip
 * sits below eye level that end draws lower, so the whole level reads as tilted
 * with the cursor centred. The side faces come from the cursor parallax and
 * from the stage sitting off the camera's axis.
 */
const STAGE_YAW = 0;
const STAGE_PITCH = 0.18;

/** Every body is extruded this deep (metres): boxes, holes, the ground strip. */
const DEPTH = 0.5;
const HALF_D = DEPTH / 2;

const CELL = 0.22; // the GAN's raster: the smallest block edge
const GROUND_FROM = -8.6;
const GROUND_TO = 4;

// One level's cycle, in seconds.
const NOISE_IN = 0.5; //    0 → noise fades in
const RESOLVE = 1.3; //       noise resolves into the structure's raster
const BUILD_FROM = 1.0; //    blocks start dropping
const BUILD_TO = 2.6; //      last block landed
const DROP = 0.42; //         one block's fall
const AIM = 0.9; //           bird pulled back in the sling
const REST = 1.0; //          rubble holds after the bake ends
const FADE = 0.6; //          everything fades out
const POP = 0.4; //           a pig's burst

// ---------------------------------------------------------------------------
// Data
// ---------------------------------------------------------------------------
interface BakedFile {
  fps: number;
  levels: {
    bodies: [number, number, number, number][];
    frames: number;
    tracks: number[][];
    bird: number[];
    launch: number;
    impact: number;
    pops: number[];
    sling: [number, number];
  }[];
}

interface Level {
  /** kind 0 block, 1 hole block, 2 pig. */
  kind: Uint8Array;
  w: Float32Array;
  h: Float32Array;
  mat: Uint8Array;
  frames: number;
  /** Absolute poses in metres/radians: body-major, frames × (x, y, angle). */
  pose: Float32Array;
  bird: Float32Array;
  launch: number;
  impact: number;
  pops: Int16Array;
  slingX: number;
  slingY: number;
  /** When each body starts dropping in (seconds into the cycle). */
  dropAt: Float32Array;
  /** Raster cells: xy centre + whether the structure fills it. */
  cells: Float32Array;
  filled: Uint8Array;
  /** Per cell: which body's arrival extinguishes it (−1: noise). */
  cellBody: Int16Array;
  cycle: number;
}

/** Undo the bake's delta encoding, in place: running sum per channel. */
const undelta = (src: number[], stride: number, scale: number) => {
  const out = new Float32Array(src.length);
  const acc = new Array<number>(stride).fill(0);
  for (let i = 0; i < src.length; i++) {
    const c = i % stride;
    acc[c]! += src[i]!;
    out[i] = acc[c]! * scale;
  }
  return out;
};

const buildLevel = (raw: BakedFile["levels"][number], fps: number): Level => {
  const n = raw.bodies.length;
  const kind = new Uint8Array(n);
  const w = new Float32Array(n);
  const h = new Float32Array(n);
  const mat = new Uint8Array(n);
  const pose = new Float32Array(n * raw.frames * 3);
  raw.bodies.forEach(([k, bw, bh, m], i) => {
    kind[i] = k;
    w[i] = bw / 100;
    h[i] = bh / 100;
    mat[i] = m;
    pose.set(undelta(raw.tracks[i]!, 3, 0.01), i * raw.frames * 3);
  });

  // Drop order: bottom-up, then left to right, the way a structure is built
  // and the way the decoder reads the grid. Pigs after every block.
  const at = (i: number) => i * raw.frames * 3;
  const order = [...Array(n).keys()].sort((a, b) => {
    const pa = kind[a] === 2 ? 1 : 0;
    const pb = kind[b] === 2 ? 1 : 0;
    if (pa !== pb) return pa - pb;
    const ya = pose[at(a) + 1]! - h[a]! / 2;
    const yb = pose[at(b) + 1]! - h[b]! / 2;
    return Math.abs(ya - yb) > 0.05 ? ya - yb : pose[at(a)]! - pose[at(b)]!;
  });
  const dropAt = new Float32Array(n);
  const span = BUILD_TO - DROP - BUILD_FROM;
  order.forEach((body, rank) => {
    dropAt[body] = BUILD_FROM + (rank / Math.max(1, n - 1)) * span;
  });

  // The raster over the structure's footprint, one margin cell all round. A
  // cell is "filled" when its centre falls inside a block's settled rectangle;
  // it then stays lit until that block lands on it.
  let minX = Infinity;
  let maxX = -Infinity;
  let maxY = 0;
  for (let i = 0; i < n; i++) {
    const x = pose[at(i)]!;
    const y = pose[at(i) + 1]!;
    minX = Math.min(minX, x - w[i]! / 2);
    maxX = Math.max(maxX, x + w[i]! / 2);
    maxY = Math.max(maxY, y + h[i]! / 2);
  }
  const cols = Math.ceil((maxX - minX) / CELL) + 2;
  const rows = Math.ceil(maxY / CELL) + 1;
  const cells = new Float32Array(cols * rows * 2);
  const filled = new Uint8Array(cols * rows);
  const cellBody = new Int16Array(cols * rows).fill(-1);
  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < cols; c++) {
      const idx = r * cols + c;
      const cx = minX + (c - 0.5) * CELL;
      const cy = (r + 0.5) * CELL;
      cells[idx * 2] = cx;
      cells[idx * 2 + 1] = cy;
      for (let i = 0; i < n; i++) {
        const bx = pose[at(i)]!;
        const by = pose[at(i) + 1]!;
        if (Math.abs(cx - bx) <= w[i]! / 2 && Math.abs(cy - by) <= h[i]! / 2) {
          filled[idx] = 1;
          cellBody[idx] = i;
          break;
        }
      }
    }
  }

  return {
    kind,
    w,
    h,
    mat,
    frames: raw.frames,
    pose,
    bird: undelta(raw.bird, 2, 0.01),
    launch: raw.launch,
    impact: raw.impact,
    pops: Int16Array.from(raw.pops),
    slingX: raw.sling[0] / 100,
    slingY: raw.sling[1] / 100,
    dropAt,
    cells,
    filled,
    cellBody,
    cycle: BUILD_TO + AIM + raw.frames / fps + REST + FADE,
  };
};

// ---------------------------------------------------------------------------
// Drawing
// ---------------------------------------------------------------------------
interface Ink {
  hills: LineField[];
  materials: LinkPool[];
  pigs: LinkPool;
  bird: LinkPool;
  fx: LinkPool;
  rig: LineField;
  grid: DotField;
  puffs: DotField;
  dispose(): void;
}

const levels = shallowRef<Level[]>([]);
const ink = shallowRef<Ink | null>(null);
let fps = 20;
let disposed = false;

const HOLE_SEGS = 12;
const PIG_SEGS = 16;
const BIRD_SEGS = 12;
const PUFFS = 28;

/**
 * The backdrop every Angry Birds level is played against: rolling hills in
 * bands receding from the ground, the near ones lower and brighter. Built once,
 * in the stage's metres, deep behind the structure so the stage's turn and the
 * cursor parallax slide the bands past each other.
 */
const HILL_LAYERS = [
  { z: -3, amp: 0.55, base: 0.6, freq: 0.42, seed: 1.3, opacity: 0.42 },
  { z: -6.5, amp: 0.9, base: 1.3, freq: 0.27, seed: 4.1, opacity: 0.28 },
  { z: -11, amp: 1.4, base: 2.2, freq: 0.17, seed: 7.7, opacity: 0.18 },
];
const HILL_FROM = -16;
const HILL_TO = 12;
const HILL_STEPS = 90;
const GRASS = 70;

const hillLine = (l: (typeof HILL_LAYERS)[number], grass: boolean) => {
  const pts: number[] = [];
  const yAt = (x: number) =>
    l.base +
    l.amp *
      (0.55 * Math.sin(x * l.freq + l.seed) +
        0.3 * Math.sin(x * l.freq * 2.3 + l.seed * 2.1) +
        0.15 * Math.sin(x * l.freq * 5.1 + l.seed * 3.7));
  for (let i = 0; i < HILL_STEPS; i++) {
    const x0 = HILL_FROM + ((HILL_TO - HILL_FROM) * i) / HILL_STEPS;
    const x1 = HILL_FROM + ((HILL_TO - HILL_FROM) * (i + 1)) / HILL_STEPS;
    pts.push(x0, yAt(x0), l.z, x1, yAt(x1), l.z);
  }
  // Grass along the near band's crest: short ticks, each leaning its own way.
  if (grass) {
    for (let i = 0; i < GRASS; i++) {
      const x = HILL_FROM + (HILL_TO - HILL_FROM) * rand01(`gr${i}`);
      const y = yAt(x);
      const lean = (rand01(`gl${i}`) - 0.5) * 0.18;
      pts.push(x, y, l.z, x + lean, y + 0.14 + 0.12 * rand01(`gh${i}`), l.z);
    }
  }
  return new Float32Array(pts);
};

const createInk = (all: Level[]): Ink => {
  const maxBodies = Math.max(...all.map((l) => l.kind.length));
  const maxCells = Math.max(...all.map((l) => l.filled.length));
  const hills = HILL_LAYERS.map((l, i) =>
    createLines(hillLine(l, i === 0), { color: HILLS })
  );
  // Boxes: 12 edges; hole blocks add a ring on each face.
  const materials = MATERIAL_COLORS.map((color) =>
    createLinkPool(maxBodies * (12 + HOLE_SEGS * 2), { color })
  );
  // Pigs and the bird are balls: three great circles each, plus a snout.
  const pigs = createLinkPool(maxBodies * (PIG_SEGS * 3 + 8), { color: PIG });
  const bird = createLinkPool(BIRD_SEGS * 3 + 4, { color: BIRD });
  const fx = createLinkPool(maxBodies * 8, { color: PIG });

  // The rig: the ground strip's front and back edges, then the slingshot
  // (3 segments, written per level) and its two rubber bands (every frame).
  const rig = createLines(new Float32Array(7 * 6), { color: RIG });
  const edge = HALF_D * 1.6;
  rig.position.set([
    GROUND_FROM, 0, edge, GROUND_TO, 0, edge,
    GROUND_FROM, 0, -edge, GROUND_TO, 0, -edge,
  ]);

  const grid = createDots(maxCells, { color: RIG, hot: "#e4d4ff" });
  grid.size.fill(0.05);
  grid.flush({ size: true });

  const puffs = createDots(PUFFS, { color: HOT, hot: HOT });
  puffs.size.fill(0.07);
  puffs.flush({ size: true });

  return {
    hills,
    materials,
    pigs,
    bird,
    fx,
    rig,
    grid,
    puffs,
    dispose() {
      hills.forEach((h) => h.dispose());
      materials.forEach((m) => m.dispose());
      pigs.dispose();
      bird.dispose();
      fx.dispose();
      rig.dispose();
      grid.dispose();
      puffs.dispose();
    },
  };
};

/** Slingshot: a post and two forks, in the rig buffer after the ground line. */
const writeSling = (rig: LineField, sx: number, sy: number) => {
  const p = rig.position;
  const fork = sy + 0.05;
  const segs = [
    [sx, 0, sx, fork - 0.3],
    [sx, fork - 0.3, sx - 0.2, fork],
    [sx, fork - 0.3, sx + 0.18, fork + 0.04],
  ];
  segs.forEach(([ax, ay, bx, by], s) => {
    const o = 12 + s * 6;
    p[o] = ax!;
    p[o + 1] = ay!;
    p[o + 2] = 0;
    p[o + 3] = bx!;
    p[o + 4] = by!;
    p[o + 5] = 0;
  });
  rig.attr.needsUpdate = true;
};

/** Rubber bands from the forks to wherever the bird sits. */
const writeBands = (
  rig: LineField,
  sx: number,
  sy: number,
  bx: number,
  by: number,
  on: boolean
) => {
  const p = rig.position;
  const fork = sy + 0.05;
  const ends = on
    ? [
        [sx - 0.2, fork, bx, by],
        [sx + 0.18, fork + 0.04, bx, by],
      ]
    : [
        [sx - 0.2, fork, sx - 0.2, fork],
        [sx + 0.18, fork + 0.04, sx + 0.18, fork + 0.04],
      ];
  ends.forEach(([ax, ay, cx, cy], s) => {
    const o = 30 + s * 6;
    p[o] = ax!;
    p[o + 1] = ay!;
    p[o + 2] = 0.01;
    p[o + 3] = cx!;
    p[o + 4] = cy!;
    p[o + 5] = 0.01;
  });
  rig.attr.needsUpdate = true;
};

const circle = (
  pool: LinkPool,
  cx: number,
  cy: number,
  r: number,
  segs: number,
  z = 0
) => {
  for (let s = 0; s < segs; s++) {
    const a0 = (s / segs) * Math.PI * 2;
    const a1 = ((s + 1) / segs) * Math.PI * 2;
    pool.push(
      cx + Math.cos(a0) * r, cy + Math.sin(a0) * r, z,
      cx + Math.cos(a1) * r, cy + Math.sin(a1) * r, z
    );
  }
};

/** A ball: the face-on circle plus two great circles turned with the body, so
 *  a rolling pig visibly rolls. */
const ball = (
  pool: LinkPool,
  cx: number,
  cy: number,
  r: number,
  segs: number,
  angle: number
) => {
  circle(pool, cx, cy, r, segs);
  const ca = Math.cos(angle);
  const sa = Math.sin(angle);
  for (let s = 0; s < segs; s++) {
    const a0 = (s / segs) * Math.PI * 2;
    const a1 = ((s + 1) / segs) * Math.PI * 2;
    const u0 = Math.cos(a0) * r;
    const u1 = Math.cos(a1) * r;
    const z0 = Math.sin(a0) * r;
    const z1 = Math.sin(a1) * r;
    // The ring through the body's local x axis and the depth axis…
    pool.push(cx + u0 * ca, cy + u0 * sa, z0, cx + u1 * ca, cy + u1 * sa, z1);
    // …and the one through its local y axis.
    pool.push(cx - u0 * sa, cy + u0 * ca, z0, cx - u1 * sa, cy + u1 * ca, z1);
  }
};

onMounted(async () => {
  try {
    const data = await $fetch<BakedFile>(DATA_URL);
    if (disposed || !data.levels?.length) return;
    fps = data.fps;
    const built = data.levels.map((l) => buildLevel(l, data.fps));
    ink.value = createInk(built);
    levels.value = built;
  } catch (err) {
    console.warn(`[StructureGen] could not load ${DATA_URL}`, err);
  }
});

// ---------------------------------------------------------------------------
// Playback
// ---------------------------------------------------------------------------
const groupRef = shallowRef<Group | null>(null);
const stageRef = shallowRef<Group | null>(null);
let curX = 0;
let curY = 0;
/** Seconds into the current level's cycle; only advances while visible. */
let clock = 0;
let levelIndex = 0;
let wasVisible = false;
let slingFor = -1;

const { onBeforeRender } = useLoop();
onBeforeRender(({ delta }) => {
  const group = groupRef.value;
  const stage = stageRef.value;
  const all = levels.value;
  const k = ink.value;
  if (!group || !stage) return;
  const reveal = props.reveal;
  group.visible = reveal > 0.001 && !!k && all.length > 0;
  if (!group.visible || !k) {
    // Coming back starts a fresh cycle on the NEXT level, from noise.
    if (wasVisible) {
      wasVisible = false;
      clock = 0;
      levelIndex = (levelIndex + 1) % Math.max(1, all.length);
    }
    return;
  }
  wasVisible = true;

  const still = reducedMotion.value;
  const drive = props.cardProgress ?? reveal;
  setDotScale(k.grid, height.value);
  setDotScale(k.puffs, height.value);

  const ease = approach(0.07, delta);
  curX += ((still ? 0 : pointer.value.x) - curX) * ease;
  curY += ((still ? 0 : pointer.value.y) - curY) * ease;
  stage.position.set(STAGE_OFFSET[0], STAGE_OFFSET[1], STAGE_OFFSET[2]);
  stage.rotation.set(STAGE_PITCH + curY * 0.06, STAGE_YAW + curX * 0.14, 0);
  stage.scale.setScalar(STAGE_SCALE);

  // --- The clock --------------------------------------------------------------
  // Reduced motion parks on the built structure, bird in the sling: the piece
  // still says what it is, and nothing moves.
  let level = all[levelIndex % all.length]!;
  if (still) {
    clock = BUILD_TO + AIM * 0.8;
  } else {
    clock += Math.min(delta, 0.1);
    if (clock >= level.cycle) {
      clock = 0;
      levelIndex = (levelIndex + 1) % all.length;
      level = all[levelIndex]!;
    }
  }
  const t = clock;
  if (slingFor !== levelIndex) {
    writeSling(k.rig, level.slingX, level.slingY);
    slingFor = levelIndex;
  }

  const playStart = BUILD_TO + AIM;
  const playT = t - playStart;
  const fFloat = clamp01(playT * fps / Math.max(1, level.frames - 1)) * (level.frames - 1);
  const f0 = Math.floor(fFloat);
  const f1 = Math.min(level.frames - 1, f0 + 1);
  const fr = fFloat - f0;
  const life = 1 - smoothstep(level.cycle - FADE, level.cycle, t);

  // --- Noise → raster ---------------------------------------------------------
  const gridPos = k.grid.position;
  const glow = k.grid.glow;
  const nCells = level.filled.length;
  const resolve = smoothstep(NOISE_IN * 0.6, RESOLVE, t);
  const noiseIn = smoothstep(0, NOISE_IN, t);
  for (let c = 0; c < k.grid.count; c++) {
    if (c >= nCells) {
      k.grid.size[c] = 0;
      continue;
    }
    gridPos[c * 3] = level.cells[c * 2]!;
    gridPos[c * 3 + 1] = level.cells[c * 2 + 1]!;
    gridPos[c * 3 + 2] = -0.02;
    // Latent noise: every cell flickers at its own rate until the raster
    // resolves; then only the structure's cells stay, burning bright, and each
    // goes out as the block decoded from it lands.
    const seed = rand01(`sg${c}`);
    const flicker = 0.5 + 0.5 * Math.sin(t * (7 + seed * 9) + seed * 40);
    const noise = noiseIn * flicker * (0.35 + 0.4 * seed) * (1 - resolve);
    let lit = 0;
    if (level.filled[c]) {
      const b = level.cellBody[c]!;
      const landed = smoothstep(level.dropAt[b]! + DROP * 0.7, level.dropAt[b]! + DROP + 0.25, t);
      lit = resolve * (1 - landed);
    }
    glow[c] = lit * 0.6;
    // Air cells shrink away as the raster resolves, structure cells as their
    // block lands: once the level is built, no dot is left.
    const show = Math.max(noiseIn * (1 - resolve), lit);
    k.grid.size[c] =
      still || show < 0.01
        ? 0
        : (0.026 + 0.026 * Math.max(noise, lit)) * Math.min(1, show * 1.6);
  }
  k.grid.flush({ size: true });

  // --- Bodies -----------------------------------------------------------------
  k.materials.forEach((m) => m.begin());
  k.pigs.begin();
  k.fx.begin();
  const frames = level.frames;
  for (let i = 0; i < level.kind.length; i++) {
    const start = level.dropAt[i]!;
    const d = (t - start) / DROP;
    if (d <= 0) continue;
    const base = i * frames * 3;
    const o0 = base + f0 * 3;
    const o1 = base + f1 * 3;
    const x = level.pose[o0]! + (level.pose[o1]! - level.pose[o0]!) * fr;
    let y = level.pose[o0 + 1]! + (level.pose[o1 + 1]! - level.pose[o0 + 1]!) * fr;
    const a = level.pose[o0 + 2]! + (level.pose[o1 + 2]! - level.pose[o0 + 2]!) * fr;
    // The drop: from a little above, decelerating into place.
    const land = easeOutCubic(d);
    y += (1 - land) * 0.9;

    if (level.kind[i] === 2) {
      const pop = level.pops[i]!;
      const popT = pop >= 0 ? playT - pop / fps : -1;
      if (popT >= 0) {
        // The burst: eight ticks thrown outward, gone in POP seconds.
        if (popT < POP && !still) {
          const u = popT / POP;
          const r0 = 0.2 + u * 0.5;
          for (let s = 0; s < 8; s++) {
            const ang = (s / 8) * Math.PI * 2 + 0.2;
            const c = Math.cos(ang);
            const sn = Math.sin(ang);
            const len = 0.18 * (1 - u);
            k.fx.push(x + c * r0, y + sn * r0, 0, x + c * (r0 + len), y + sn * (r0 + len), 0);
          }
        }
        continue;
      }
      // Pigs grow in rather than fall: they are placed, not stacked.
      const r = 0.25 * land;
      ball(k.pigs, x, y, r, PIG_SEGS, a);
      // A snout on the face, turning with the pig as it rolls.
      const sx = x + Math.cos(a) * r * 0.25;
      const sy = y + Math.sin(a) * r * 0.25 - r * 0.1;
      circle(k.pigs, sx, sy, r * 0.32, 8, r * 0.9);
      continue;
    }

    const pool = k.materials[level.mat[i]!]!;
    const hw = level.w[i]! / 2;
    const hh = level.h[i]! / 2;
    const ca = Math.cos(a);
    const sa = Math.sin(a);
    const cx0 = x + (-hw * ca - -hh * sa);
    const cy0 = y + (-hw * sa + -hh * ca);
    const cx1 = x + (hw * ca - -hh * sa);
    const cy1 = y + (hw * sa + -hh * ca);
    const cx2 = x + (hw * ca - hh * sa);
    const cy2 = y + (hw * sa + hh * ca);
    const cx3 = x + (-hw * ca - hh * sa);
    const cy3 = y + (-hw * sa + hh * ca);
    // Front face, back face, and the four edges joining them.
    for (const z of [HALF_D, -HALF_D]) {
      pool.push(cx0, cy0, z, cx1, cy1, z);
      pool.push(cx1, cy1, z, cx2, cy2, z);
      pool.push(cx2, cy2, z, cx3, cy3, z);
      pool.push(cx3, cy3, z, cx0, cy0, z);
    }
    pool.push(cx0, cy0, HALF_D, cx0, cy0, -HALF_D);
    pool.push(cx1, cy1, HALF_D, cx1, cy1, -HALF_D);
    pool.push(cx2, cy2, HALF_D, cx2, cy2, -HALF_D);
    pool.push(cx3, cy3, HALF_D, cx3, cy3, -HALF_D);
    if (level.kind[i] === 1) {
      circle(pool, x, y, hw * 0.62, HOLE_SEGS, HALF_D);
      circle(pool, x, y, hw * 0.62, HOLE_SEGS, -HALF_D);
    }
  }
  k.materials.forEach((m) => m.end());
  k.pigs.end();
  k.fx.end();

  // --- Bird -------------------------------------------------------------------
  k.bird.begin();
  const bf = level.bird;
  let bx = level.slingX;
  let by = level.slingY;
  let inSling = false;
  if (playT < 0) {
    // Arrives on the sling as the build finishes, then is drawn back.
    const arrive = smoothstep(BUILD_TO - 0.3, BUILD_TO + 0.2, t);
    const pull = easeOutCubic(clamp01((t - BUILD_TO) / (AIM * 0.8)));
    bx -= pull * 0.42;
    by -= pull * 0.16;
    inSling = arrive > 0.5;
    if (arrive > 0.01) ball(k.bird, bx, by, 0.22 * arrive, BIRD_SEGS, 0);
  } else {
    const o0 = f0 * 2;
    const o1 = f1 * 2;
    bx = bf[o0]! + (bf[o1]! - bf[o0]!) * fr;
    by = bf[o0 + 1]! + (bf[o1 + 1]! - bf[o0 + 1]!) * fr;
    inSling = fFloat < level.launch;
    // Spin with distance flown: the bake doesn't carry the bird's angle, and a
    // ball that slides without turning reads as a sticker.
    ball(k.bird, bx, by, 0.22, BIRD_SEGS, -(bx - level.slingX) / 0.22);
  }
  k.bird.end();
  writeBands(k.rig, level.slingX, level.slingY, bx, by, inSling);

  // Trail puffs: a dot every other frame from launch to impact, the way the
  // game marks a shot's arc, left hanging until the level fades.
  const pp = k.puffs.position;
  const lastPuff = level.impact >= 0 ? level.impact : frames - 1;
  for (let p = 0; p < PUFFS; p++) {
    const f = level.launch + 1 + p * 2;
    const shown = playT >= 0 && f <= Math.min(lastPuff, fFloat) && f < frames;
    pp[p * 3] = shown ? bf[f * 2]! : 0;
    pp[p * 3 + 1] = shown ? bf[f * 2 + 1]! : 0;
    pp[p * 3 + 2] = 0.01;
    k.puffs.size[p] = shown ? 0.05 + 0.04 * (p % 2) : 0;
  }
  k.puffs.flush({ size: true, glow: false });

  // --- Ink --------------------------------------------------------------------
  drawFraction(k.rig.geometry, k.rig.vertexCount, smoothstep(0.02, 0.3, drive));
  k.hills.forEach((h, i) => {
    // Near band first, far last: the landscape unrolls as the card arrives.
    const from = 0.04 + i * 0.06;
    drawFraction(h.geometry, h.vertexCount, smoothstep(from, from + 0.3, drive));
    h.material.opacity = HILL_LAYERS[i]!.opacity * reveal;
  });
  const alpha = reveal * life;
  k.materials.forEach((m) => (m.material.opacity = 0.85 * alpha));
  k.pigs.material.opacity = 0.9 * alpha;
  k.fx.material.opacity = 0.9 * alpha;
  // The bird has done its job a moment after impact; left in, it bounces back
  // and rolls home toward the slingshot, which reads as a glitch.
  const impactT = level.impact >= 0 ? level.impact / fps : Infinity;
  const birdLeft = 1 - smoothstep(impactT + 0.8, impactT + 1.6, playT);
  k.bird.material.opacity = 0.95 * alpha * birdLeft;
  k.rig.material.opacity = 0.55 * reveal;
  k.grid.material.uniforms.uOpacity!.value = 0.9 * alpha;
  k.puffs.material.uniforms.uOpacity!.value = 0.45 * alpha;
});

onBeforeUnmount(() => {
  disposed = true;
  ink.value?.dispose();
});
</script>

<template>
  <TresGroup ref="groupRef" :position="props.position" :visible="false">
    <TresGroup ref="stageRef">
      <template v-if="ink">
        <primitive
          v-for="(h, i) in ink.hills"
          :key="`h${i}`"
          :object="h.lines"
        />
        <primitive :object="ink.grid.points" />
        <primitive :object="ink.rig.lines" />
        <primitive
          v-for="(m, i) in ink.materials"
          :key="i"
          :object="m.lines"
        />
        <primitive :object="ink.pigs.lines" />
        <primitive :object="ink.fx.lines" />
        <primitive :object="ink.bird.lines" />
        <primitive :object="ink.puffs.points" />
      </template>
    </TresGroup>
  </TresGroup>
</template>
